services:
  casvisor:
    restart: always
    image: casbin/casvisor
    ports:
      - "16001:16001"
    depends_on:
      - db
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf:/home/casvisor/conf
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 30s # Ensures casvisor starts 30 seconds after db
        parallelism: 1
    networks:
      - default

  db:
    restart: always
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /usr/local/docker/mysql:/var/lib/mysql
    deploy:
      update_config:
        order: stop-first
        failure_action: rollback
        delay: 0s
        parallelism: 1
    networks:
      - default

  guacd:
    image: guacamole/guacd:latest
    environment:
      GUACD_LOG_LEVEL: debug
    volumes:
      - ./data/guacd:/usr/local/casvisor/data
    restart: always
    depends_on:
      - db
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 0s
        parallelism: 1
    networks:
      - default

networks:
  default:
